// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn8iVDC0O7ifanbTlzgBThyQa9rz4rHh8',
    appId: '1:1004928769738:web:a1c7af107833eb10b85e33',
    messagingSenderId: '1004928769738',
    projectId: 'doctor-booking-app-1ec74',
    authDomain: 'doctor-booking-app-1ec74.firebaseapp.com',
    storageBucket: 'doctor-booking-app-1ec74.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUJaak33-yqZXIyeQRALFoTRfPP6kwnwQ',
    appId: '1:1004928769738:android:5cab39c24740039db85e33',
    messagingSenderId: '1004928769738',
    projectId: 'doctor-booking-app-1ec74',
    storageBucket: 'doctor-booking-app-1ec74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4sY0NPlXCEuI8EML4ZPOA0MAw8pEFDOc',
    appId: '1:1004928769738:ios:d15cfc5045363477b85e33',
    messagingSenderId: '1004928769738',
    projectId: 'doctor-booking-app-1ec74',
    storageBucket: 'doctor-booking-app-1ec74.firebasestorage.app',
    iosBundleId: 'com.example.doctorBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4sY0NPlXCEuI8EML4ZPOA0MAw8pEFDOc',
    appId: '1:1004928769738:ios:d15cfc5045363477b85e33',
    messagingSenderId: '1004928769738',
    projectId: 'doctor-booking-app-1ec74',
    storageBucket: 'doctor-booking-app-1ec74.firebasestorage.app',
    iosBundleId: 'com.example.doctorBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn8iVDC0O7ifanbTlzgBThyQa9rz4rHh8',
    appId: '1:1004928769738:web:718cd54fdb171f6ab85e33',
    messagingSenderId: '1004928769738',
    projectId: 'doctor-booking-app-1ec74',
    authDomain: 'doctor-booking-app-1ec74.firebaseapp.com',
    storageBucket: 'doctor-booking-app-1ec74.firebasestorage.app',
  );
}
